---
- name: Run Terraform Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Initialize and Apply Terraform
      cloud.terraform.terraform:
        project_path: "{{ playbook_dir }}/terraform"
        state: present
        force_init: true
      register: tf_output

    - name: Debug Terraform outputs
      ansible.builtin.debug:
        var: tf_output.outputs
